[package]
name = "unconfig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Serialize|Deserialize
serde = { version = "1.0.190", default-features = false, features = [ "derive" ] }
serde_yaml = "0.9"
quick-xml = { version = "0.31.0", default-features = false, features = [ "serialize" ] }
serde_with = { version = "3.6.1", features = ["base64"] }
serde_json = { version = "1.0.113"}

# Log
tracing-log = "0.2.0"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = [ "env-filter", "std" ] }
tracing = { version = "0.1.40", features = [ "log" ] }

# Net
axum = { version = "0.7.4" }

# Runtime
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }

# Errors
anyhow = { version =  "1.0.79" }
thiserror = { version = "1.0.56" }

# Helpers
regex = "1.10.3"
base64 = "0.21.7"
